#include<stdio.h>
int main()
{
    int choice,a,name,ch,qty,rate,dis,total,totalamount,Afterdiscount,cgst,sgst,grandtotal,SubTotal,cash,change,totalbill;
 printf("\n\nHERE IS YOUR DELECIOUS MENU CARD!!!");
 printf("\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
 printf("\nSelect your drink:\n1.CAPPUCCINO \n2.ROBUSTO COFFEE \n3.COLD COFFEE \n4.EXPRESSO \n5.CAFFE MACCHIATO \n6.ARABICA \n7.TEA \n8.GINGER TEA \n9.BLACK TEA\n"); 
 printf("\nSelect your Bites:\n10.CHEESE MAX PIZZA \n11.DOUBLE CHEESE PAN PIZZA \n12.SPICY PANEER BURGER \n13.VEG CHEESE BURGER \n14.VEG SANDWITCH \n15.PANNER CHEESE SANDWITCH");
 printf("\n\nPlease select your choice : ");
 scanf("%d",&choice);
 system("clear");
 printf("\n\t\t\t-----------TAX INVOICE------------");
 printf("\n\t\t\tDATE:18/08/2023\t\tTABLE NO:5");
 printf("\n\t\t\tBILL NO:101");
 printf("\n\t\t\t----------------------------------");
 printf("\n\t\t\t==================================");
 printf("\n\t\t\t~~~~~WELCOME TO COADING CAFE~~~~~~\n\n\t\t\tOff Kanakapura Road,Doddakalsandra\n\t\t\tVasanthpura,Bengaluru-62");
 printf("\n\t\t\t==================================");
 printf("\n\n*******************************************************************************");
 printf("\n*ALERT*\nSPECIAL OFFER IS GOING ON !!!\nSELECT ANY DRINKS OR BITES MORE THAN 5 PIECES YOU WILL GET FLAT 10 PERCENT OFF!\n*OFFER IS FOR LIMITED PERIOD ONLY* ");
 printf("\n*******************************************************************************");
 
 switch(choice)
 {
  case 1:
    printf("\n\nYou have selected CAPPUCCINO.\nEnter the quantity : ");
    scanf("%d",&qty);
    printf("Rate : 225.00");
    float rate=225.00; 
    float total=qty*rate;
    float netTotal=qty*rate;
    float cgst=0.05*netTotal,grandtotal=totalamount + 2*cgst;
    printf("\n\n-----------------------------------------------");
    printf("\nSub Total\t\t\t      : %.2f",total);
    printf("\nPlease Enter the discount percentage  : ");
    scanf("%d",&dis);
    Afterdiscount=total-(total*dis/100);
    printf("After discount your bill amount is    : %d",Afterdiscount);
    printf("\nCGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\nSGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\n-----------------------------------------------");
    printf("\nGRAND TOTAL\t\t\t      : %.2f",Afterdiscount+2*cgst);
    printf("\n-----------------------------------------------");
    break;
  case 2:
    printf("\n\nYou have selected ROBUSTO COFFEE.\nEnter the quantity : ");
    scanf("%d",&qty);
    printf("Rate : 450.00");
    rate=450.00;
    total=qty*rate;
    netTotal=qty*rate;
    cgst=0.05*netTotal,grandtotal=totalamount + 2*cgst;
    printf("\n\n-----------------------------------------------");
    printf("\nSub Total\t\t\t      : %.2f",total);
    printf("\nPlease Enter the discount percentage  : ");
    scanf("%d",&dis);
    Afterdiscount=total-(total*dis/100);
    printf("After discount your bill amount is    : %d",Afterdiscount);
    printf("\nCGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\nSGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\n-----------------------------------------------");
    printf("\nGRAND TOTAL\t\t\t      : %.2f",Afterdiscount+2*cgst);
    printf("\n-----------------------------------------------");
  case 3:
    printf("\nYou have selected Cold coffee.\nEnter the quantity :");
    scanf("%d",&qty);
    printf("Rate : 180.00");
    rate=180.00;
    total=qty*rate;
    netTotal=qty*rate;
    cgst=0.05*netTotal,grandtotal=totalamount + 2*cgst;
    printf("\n\n-----------------------------------------------");
    printf("\nSub Total\t\t\t      : %.2f",total);
    printf("\nPlease Enter the discount percentage  : ");
    scanf("%d",&dis);
    Afterdiscount=total-(total*dis/100);
    printf("After discount your bill amount is    : %d",Afterdiscount);
    printf("\nCGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\nSGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\n-----------------------------------------------");
    printf("\nGRAND TOTAL\t\t\t      : %.2f",Afterdiscount+2*cgst);
    printf("\n-----------------------------------------------");
    break;
  case 4:
    printf("\nYou have selected EXPRESSO.\nEnter the quantity :");
    scanf("%d",&qty);
    printf("Rate : 450.00");
    rate=450.00;
    total=qty*rate;
    netTotal=qty*rate;
    cgst=0.05*netTotal,grandtotal=totalamount + 2*cgst;
    printf("\n\n-----------------------------------------------");
    printf("\nSub Total\t\t\t      : %.2f",total);
    printf("\nPlease Enter the discount percentage  : ");
    scanf("%d",&dis);
    Afterdiscount=total-(total*dis/100);
    printf("After discount your bill amount is    : %d",Afterdiscount);
    printf("\nCGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\nSGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\n-----------------------------------------------");
    printf("\nGRAND TOTAL\t\t\t      : %.2f",Afterdiscount+2*cgst);
    printf("\n-----------------------------------------------");
    break;
  case 5:
    printf("\nYou have selected CAFFE MACCHIATO.\nEnter the quantity :");
    scanf("%d",&qty);
    printf("Rate : 300.00");
    rate=300.00;
    total=qty*rate;
    netTotal=qty*rate;
    cgst=0.05*netTotal,grandtotal=totalamount + 2*cgst;
    printf("\n\n-----------------------------------------------");
    printf("\nSub Total\t\t\t      : %.2f",total);
    printf("\nPlease Enter the discount percentage  : ");
    scanf("%d",&dis);
    Afterdiscount=total-(total*dis/100);
    printf("After discount your bill amount is    : %d",Afterdiscount);
    printf("\nCGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\nSGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\n-----------------------------------------------");
    printf("\nGRAND TOTAL\t\t\t      : %.2f",Afterdiscount+2*cgst);
    printf("\n-----------------------------------------------");
    break;
  case 6:
    printf("\nYou have selected ARABICA.\nEnter the quantity :");
    scanf("%d",&qty);
    printf("Rate : 250.00");
    rate=250.00;
    total=qty*rate;
    netTotal=qty*rate;
    cgst=0.05*netTotal,grandtotal=totalamount + 2*cgst;
    printf("\n\n-----------------------------------------------");
    printf("\nSub Total\t\t\t      : %.2f",total);
    printf("\nPlease Enter the discount percentage  : ");
    scanf("%d",&dis);
    Afterdiscount=total-(total*dis/100);
    printf("After discount your bill amount is    : %d",Afterdiscount);
    printf("\nCGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\nSGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\n-----------------------------------------------");
    printf("\nGRAND TOTAL\t\t\t      : %.2f",Afterdiscount+2*cgst);
    printf("\n-----------------------------------------------");
    break;
  case 7:
    printf("\nYou have selected TEA.\nEnter the quantity :");
    scanf("%d",&qty);
    printf("Rate : 100.00");
    rate=100.00;
    total=qty*rate;
    netTotal=qty*rate;
    cgst=0.05*netTotal,grandtotal=totalamount + 2*cgst;
    printf("\n\n-----------------------------------------------");
    printf("\nSub Total\t\t\t      : %.2f",total);
    printf("\nPlease Enter the discount percentage  : ");
    scanf("%d",&dis);
    Afterdiscount=total-(total*dis/100);
    printf("After discount your bill amount is    : %d",Afterdiscount);
    printf("\nCGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\nSGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\n-----------------------------------------------");
    printf("\nGRAND TOTAL\t\t\t      : %.2f",Afterdiscount+2*cgst);
    printf("\n-----------------------------------------------");
    break;
  case 8:
    printf("\nYou have selected GINGER TEA.\nEnter the quantity :");
    scanf("%d",&qty);
    printf("Rate : 150.00");
    rate=150.00;
    total=qty*rate;
    netTotal=qty*rate;
    cgst=0.05*netTotal,grandtotal=totalamount + 2*cgst;
    printf("\n\n-----------------------------------------------");
    printf("\nSub Total\t\t\t      : %.2f",total);
    printf("\nPlease Enter the discount percentage  : ");
    scanf("%d",&dis);
    Afterdiscount=total-(total*dis/100);
    printf("After discount your bill amount is    : %d",Afterdiscount);
    printf("\nCGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\nSGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\n-----------------------------------------------");
    printf("\nGRAND TOTAL\t\t\t      : %.2f",Afterdiscount+2*cgst);
    printf("\n-----------------------------------------------");
    break;
  case 9:
    printf("\nYou have selected BLACK TEA.\nEnter the quantity :");
    scanf("%d",&qty);
    printf("Rate : 200.00");
    rate=200.00;
    total=qty*rate;
    netTotal=qty*rate;
    cgst=0.05*netTotal,grandtotal=totalamount + 2*cgst;
    printf("\n\n-----------------------------------------------");
    printf("\nSub Total\t\t\t      : %.2f",total);
    printf("\nPlease Enter the discount percentage  : ");
    scanf("%d",&dis);
    Afterdiscount=total-(total*dis/100);
    printf("After discount your bill amount is    : %d",Afterdiscount);
    printf("\nCGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\nSGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\n-----------------------------------------------");
    printf("\nGRAND TOTAL\t\t\t      : %.2f",Afterdiscount+2*cgst);
    printf("\n-----------------------------------------------");
    break;
  case 10:
    printf("\nYou have selected CHEESE MAX PIZZA.\nEnter the quantity :");
    scanf("%d",&qty);
    printf("Rate : 350.00");
    rate=350.00;
    total=qty*rate;
    netTotal=qty*rate;
    cgst=0.05*netTotal,grandtotal=totalamount + 2*cgst;
    printf("\n\n-----------------------------------------------");
    printf("\nSub Total\t\t\t      : %.2f",total);
    printf("\nPlease Enter the discount percentage  : ");
    scanf("%d",&dis);
    Afterdiscount=total-(total*dis/100);
    printf("After discount your bill amount is    : %d",Afterdiscount);
    printf("\nCGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\nSGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\n-----------------------------------------------");
    printf("\nGRAND TOTAL\t\t\t      : %.2f",Afterdiscount+2*cgst);
    printf("\n-----------------------------------------------");
    
  case 11:
    printf("\nYou have selected DOUBLE CHEESE PIZZA.\nEnter the quantity :");
    scanf("%d",&qty);
    printf("Rate : 400.00");
    rate=400.00;
    total=qty*rate;
    netTotal=qty*rate;
    cgst=0.05*netTotal,grandtotal=totalamount + 2*cgst;
    printf("\n\n-----------------------------------------------");
    printf("\nSub Total\t\t\t      : %.2f",total);
    printf("\nPlease Enter the discount percentage  : ");
    scanf("%d",&dis);
    Afterdiscount=total-(total*dis/100);
    printf("After discount your bill amount is    : %d",Afterdiscount);
    printf("\nCGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\nSGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\n-----------------------------------------------");
    printf("\nGRAND TOTAL\t\t\t      : %.2f",Afterdiscount+2*cgst);
    printf("\n-----------------------------------------------");
    break;
  case 12:
    printf("\nYou have selected SPICY PANNER BURGER.\nEnter the quantity :");
    scanf("%d",&qty);
    printf("Rate : 200.00");
    rate=200.00;
    netTotal=qty*rate;
    cgst=0.05*netTotal,grandtotal=totalamount + 2*cgst;
    printf("\n\n-----------------------------------------------");
    printf("\nSub Total\t\t\t      : %.2f",total);
    printf("\nPlease Enter the discount percentage  : ");
    scanf("%d",&dis);
    Afterdiscount=total-(total*dis/100);
    printf("After discount your bill amount is    : %d",Afterdiscount);
    printf("\nCGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\nSGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\n-----------------------------------------------");
    printf("\nGRAND TOTAL\t\t\t      : %.2f",Afterdiscount+2*cgst);
    printf("\n-----------------------------------------------");
    break;
  case 13:
    printf("\nYou have selected VEG CHEESE BURGER.\nEnter the quantity :");
    scanf("%d",&qty);
    printf("Rate : 250.00");
    rate=250.00;
    total=qty*rate;
    netTotal=qty*rate;
    cgst=0.05*netTotal,grandtotal=totalamount + 2*cgst;
    printf("\n\n-----------------------------------------------");
    printf("\nSub Total\t\t\t      : %.2f",total);
    printf("\nPlease Enter the discount percentage  : ");
    scanf("%d",&dis);
    Afterdiscount=total-(total*dis/100);
    printf("After discount your bill amount is    : %d",Afterdiscount);
    printf("\nCGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\nSGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\n-----------------------------------------------");
    printf("\nGRAND TOTAL\t\t\t      : %.2f",Afterdiscount+2*cgst);
    printf("\n-----------------------------------------------");
    break;
  case 14:
    printf("\nYou have selected VEG SANDWITCH.\nEnter the quantity :");
    scanf("%d",&qty);
    printf("Rate : 150.00");
    rate=150.00;
    total=qty*rate;
    netTotal=qty*rate;
    cgst=0.05*netTotal,grandtotal=totalamount + 2*cgst;
    printf("\n\n-----------------------------------------------");
    printf("\nSub Total\t\t\t      : %.2f",total);
    printf("\nPlease Enter the discount percentage  : ");
    scanf("%d",&dis);
    Afterdiscount=total-(total*dis/100);
    printf("After discount your bill amount is    : %d",Afterdiscount);
    printf("\nCGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\nSGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\n-----------------------------------------------");
    printf("\nGRAND TOTAL\t\t\t      : %.2f",Afterdiscount+2*cgst);
    printf("\n-----------------------------------------------");
    break;
  case 15:
    printf("\nYou have selected PANNER CHEESE SANDWITCH.\nEnter the quantity :");
    scanf("%d",&qty);
    printf("Rate : 250.00");
    rate=250.00;
    total=qty*rate;
    netTotal=qty*rate;
    cgst=0.05*netTotal,grandtotal=totalamount + 2*cgst;
    printf("\n\n-----------------------------------------------");
    printf("\nSub Total\t\t\t      : %.2f",total);
    printf("\nPlease Enter the discount percentage  : ");
    scanf("%d",&dis);
    Afterdiscount=total-(total*dis/100);
    printf("After discount your bill amount is    : %d",Afterdiscount);
    printf("\nCGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\nSGST @5%s\t\t\t      : %.2f","%",cgst);
    printf("\n-----------------------------------------------");
    printf("\nGRAND TOTAL\t\t\t      : %.2f",Afterdiscount+2*cgst);
    printf("\n-----------------------------------------------");
    printf("\nCash tendered\t: ");
    scanf("%d",&cash);
    change = cash- Afterdiscount+2*cgst;
    printf("\nChange\t\t: %.2d",change);
    break;
  default:
    printf("\nSorry Unavailable:)...%ds",a);
    break;
 }
 printf("\nChange\t\t: %.2d",change);
 printf("\n\n\t  ***HAVE A GOOD DAY***");
 printf("\n\tTHANK YOU FOR VISITING!!!");
 printf("\n\t       VISIT AGAIN!");
 return 0;
}